export const QuoteValidationExceptions = {
    QUOTE_REQUIRED: "Quote is required",
    DATE_REQUIRED: "Date is required",
    CUSTOMER_REQUIRED: "Customer is required",
    SITE_DELIVERY_REQUIRED: "Site / Delivery is required",
    NO_QUOTES_REQUIRED: "No. Quotes is required",
    SUB_TOTAL_REQUIRED: "Sub Total is required",
    VAT_REQUIRED: "VAT is required",
    TOTAL_REQUIRED: "Total is required",
    DEPOSIT_REQUIRED: "Deposit is required",
    OUTSTANDING_REQUIRED: "Outstanding is required",
    PROFIT_REQUIRED: "Profit is required",
    EMAIL_REQUIRED: "Email is required",
    DESCRIPTION_REQUIRED: "Description is required",
    JOB_REF_REQUIRED: "Customer Job Ref is required",

    INVALID_EMAIL: "Email is invalid",
    INVALID_DATE: "Date is invalid",
    INVALID_SUB_TOTAL: "Sub Total is invalid",
    INVALID_VAT: "VAT is invalid",
    INVALID_TOTAL: "Total is invalid",
    INVALID_DEPOSIT: "Deposit is invalid",
    INVALID_OUTSTANDING: "Outstanding is invalid",
    INVALID_PROFIT: "Profit is invalid",

    SHORT_NAME: "Name is too short",
};